C:\Install\R\Rscript.exe

C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\packages.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_bdi.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_bdi_matched.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_bwa.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_bwa_matched.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_civ.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_civ_matched.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_cod.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_cod_matched.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_lso.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_lso_matched.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_mwi.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_mwi_matched.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_swz.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_swz_matched.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_tnz.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_tnz_matched.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_zaf.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_zaf_matched.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_idn.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_idn_matched.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_kaz.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_kaz_matched.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_kgz.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_kgz_matched.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_tjk.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_tjk_matched.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_npl.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_npl_matched.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_mmr.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_mmr_matched.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_phl.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_phl_matched.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_bfa.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_bfa_matched.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_gha.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_gha_matched.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_lbr.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_lbr_matched.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_mli.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_mli_matched.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_sen.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_sen_matched.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_tgo.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\orgunits_tgo_matched.R
C:\Users\bbetz\Projects\custom_indicator_reporting_project\custom_indicator\Scripts\z_bind_export.R




